// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test_link
NumericVector test_link(NumericVector x, std::string linkType, double k);
RcppExport SEXP gpuglm_test_link(SEXP xSEXP, SEXP linkTypeSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type linkType(linkTypeSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    __result = Rcpp::wrap(test_link(x, linkType, k));
    return __result;
END_RCPP
}
// test_inv_link
NumericVector test_inv_link(NumericVector x, std::string linkType, double k);
RcppExport SEXP gpuglm_test_inv_link(SEXP xSEXP, SEXP linkTypeSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type linkType(linkTypeSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    __result = Rcpp::wrap(test_inv_link(x, linkType, k));
    return __result;
END_RCPP
}
