# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_link <- function(x, linkType, k = 0) {
    .Call('gpuglm_test_link', PACKAGE = 'gpuglm', x, linkType, k)
}

test_inv_link <- function(x, linkType, k = 0) {
    .Call('gpuglm_test_inv_link', PACKAGE = 'gpuglm', x, linkType, k)
}

